# Generated by Django 4.1.5 on 2024-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('repair_status', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('view_dashboard', 'Can View Dashboard'), ('book_device', 'Can Book Device'), ('update_repair_status', 'Can Update Repair Status'), ('see_booking_available', 'Can See Booking Available')],
            },
        ),
    ]
